version: "3.9"
services:
  redis:
    container_name: redis_bloom_moby_dick
    image: "redis/redis-stack-server:latest"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure